name: Linter
on: [push]
jobs:
  update_prettier:
    runs-on: ubuntu-latest
    steps:
      # make your repository's code available to the action
      - uses: actions/checkout@v1
      # setup Node 12. Change the version number to your preference
      - uses: actions/setup-node@v1
        with:
          version: 12
      # Install your package dependencies
      - run: npm ci --prefix .\client\
      # Fix linting errors with the new prettier version
      - run: npm run --prefix .\client\ lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Linter"
          body: "Linter next.js"
          branch: ${{ github.ref }}
          commit-message: "linter: next"
